### ISSUE TITLE
KeyError in '_p_resolveConflict'

### ISSUE THREAD

**Issue by tseaver** [repoze/repoze.session#2]
It has shown up in several KARL deployments:

```
Traceback (most recent call last):
File ".../ZODB/ConflictResolution.py", line 258, in tryToResolveConflict
  resolved = resolve(old, committed, newstate)
File ".../repoze.session-0.1-py2.6.egg/repoze/session/data.py", line 101, in _p_resolveConflict
  if committed['_container'] != new['_container']:
KeyError: '_container'
```

**Comment by tseaver** [comment]
Should be fixed in 0.3.
